apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2021-05-24T10:28:08Z
  name: kiali-pod-chaos
  version: 0.1.0
  annotations:
    categories: kiali-pod-chaos
    chartDescription: Injects chaos on kiali application using cmd probe.
spec:
  displayName: Kiali-Chaos
  categoryDescription: >
    It generate loads, inject chaos on kiali,
    uninstall the application and revert the chaos
  experiments:
    - pod-delete
    - pod-cpu-hog
    - pod-memory-hog
  keywords:
    - Kubernetes
    - Kiali
    - Pod
    - Memory
    - CPU
    - Network
  platforms:
    - GKE
    - Minikube
    - Packet(Kubeadm)
    - EKS
    - AKS
  maintainers:
    - name: lamc
      email: crystal.lam@dowjones.com
  provider:
    name: ChaosNative
  links:
    - name: PIB Slack
      url: https://app.slack.com/client/T025QN6JG/C03RN9TSG
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/chaoshub/#generic-chaos
  icon:
    - url:
      mediatype: image/png
